//! # TinTin Mini-App SDK
//!
//! This crate provides the core types and runtime logic for the
//! TinTin Mini-App system — a sandboxed WebView-based third-party
//! app platform, inspired by WeChat Mini Programs.
//!
//! **License:** MIT — third-party developers may freely use this SDK.
//!
//! ## Overview
//!
//! A mini-app is a signed ZIP archive (`.tma`) containing HTML, CSS,
//! and JavaScript, loaded into a sandboxed WebView. Communication with
//! the host app goes through a typed JS bridge (`window.TinTin`).
//!
//! This crate defines the wire-format types for that bridge, the
//! manifest format, permission model, and sandbox configuration.

use serde::{Deserialize, Serialize};

// ═══════════════════════════════════════════════════════════════════
// Manifest
// ═══════════════════════════════════════════════════════════════════

/// Parsed `manifest.json` from a `.tma` package.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MiniAppManifest {
    pub app_id: String,
    pub name: String,
    pub version: String,
    #[serde(default)]
    pub description: String,
    pub icon: String,
    #[serde(default = "default_entry")]
    pub entry: String,
    #[serde(default)]
    pub permissions: Vec<String>,
    #[serde(default)]
    pub size_bytes: u64,
    #[serde(default)]
    pub developer: Option<DeveloperInfo>,
}

fn default_entry() -> String {
    "index.html".to_string()
}

/// Developer metadata from the manifest.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeveloperInfo {
    pub name: String,
    #[serde(default)]
    pub website: String,
}

// ═══════════════════════════════════════════════════════════════════
// Permission model
// ═══════════════════════════════════════════════════════════════════

/// Well-known permission identifiers.
pub mod permissions {
    pub const PROFILE_READ: &str = "user.profile.read";
    pub const LOCATION: &str = "user.location";
    pub const SEND_MESSAGE: &str = "message.send";
    pub const CAMERA: &str = "media.camera";
    pub const GALLERY: &str = "media.gallery";
    pub const NETWORK: &str = "network.request";
}

/// A set of granted permissions for a running mini-app.
#[derive(Debug, Clone, Default)]
pub struct PermissionSet {
    granted: std::collections::HashSet<String>,
}

impl PermissionSet {
    pub fn new() -> Self {
        Self::default()
    }

    /// Grant a permission (from manifest or user consent).
    pub fn grant(&mut self, perm: &str) {
        self.granted.insert(perm.to_string());
    }

    /// Check whether a permission is granted.
    pub fn check(&self, perm: &str) -> bool {
        self.granted.contains(perm)
    }

    /// Return all currently granted permissions.
    pub fn list(&self) -> Vec<&str> {
        let mut v: Vec<&str> = self.granted.iter().map(|s| s.as_str()).collect();
        v.sort();
        v
    }
}

// ═══════════════════════════════════════════════════════════════════
// JS Bridge protocol types
// ═══════════════════════════════════════════════════════════════════

/// A request sent from the mini-app WebView to the host.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JsBridgeRequest {
    /// Unique request ID (generated by the mini-app).
    pub id: String,
    /// Method name in dotted notation, e.g. `"user.getProfile"`.
    pub method: String,
    /// Parameters as a JSON object.
    pub params: serde_json::Value,
}

/// A successful response from the host to the mini-app.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JsBridgeResponse {
    /// Matching the request `id`.
    pub id: String,
    /// The result value (any valid JSON).
    pub result: serde_json::Value,
}

/// An error response from the host.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JsBridgeError {
    /// Matching the request `id`.
    pub id: String,
    /// Error details.
    pub error: JsError,
}

/// Error payload for a failed bridge call.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JsError {
    pub code: i32,
    pub message: String,
}

/// Enum over all possible bridge responses.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum JsBridgeOutcome {
    Success(JsBridgeResponse),
    Error(JsBridgeError),
}

// ═══════════════════════════════════════════════════════════════════
// User Profile types
// ═══════════════════════════════════════════════════════════════════

/// User profile returned by `user.getProfile`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserProfile {
    pub id: String,
    pub display_name: String,
    pub avatar_url: String,
    pub language: String,
}

// ═══════════════════════════════════════════════════════════════════
// Sandbox configuration
// ═══════════════════════════════════════════════════════════════════

/// Configuration for the WebView sandbox environment.
#[derive(Debug, Clone)]
pub struct SandboxConfig {
    /// Base path to the unpacked mini-app directory.
    pub app_dir: String,
    /// Permissions granted to this mini-app.
    pub permissions: PermissionSet,
    /// Maximum storage quota in bytes (default 10 MB).
    pub storage_quota: u64,
    /// Allowed network domains (from manifest or developer config).
    pub allowed_domains: Vec<String>,
}

impl Default for SandboxConfig {
    fn default() -> Self {
        Self {
            app_dir: String::new(),
            permissions: PermissionSet::new(),
            storage_quota: 10 * 1024 * 1024, // 10 MB
            allowed_domains: Vec::new(),
        }
    }
}

impl SandboxConfig {
    /// Create a config from a manifest and the app directory path.
    pub fn from_manifest(manifest: &MiniAppManifest, app_dir: &str) -> Self {
        let mut perms = PermissionSet::new();
        for p in &manifest.permissions {
            perms.grant(p);
        }
        Self {
            app_dir: app_dir.to_string(),
            permissions: perms,
            ..Default::default()
        }
    }
}

// ═══════════════════════════════════════════════════════════════════
// Mini-App Package validation
// ═══════════════════════════════════════════════════════════════════

/// Errors that can occur when validating a mini-app package.
#[derive(Debug, Clone)]
pub enum PackageError {
    InvalidManifest(String),
    MissingEntry,
    IconTooLarge,
    PackageTooLarge,
    PermissionNotRecognized(String),
}

impl std::fmt::Display for PackageError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::InvalidManifest(s) => write!(f, "invalid manifest: {s}"),
            Self::MissingEntry => write!(f, "entry file not found in package"),
            Self::IconTooLarge => write!(f, "icon exceeds maximum size"),
            Self::PackageTooLarge => write!(f, "package exceeds 5 MB limit"),
            Self::PermissionNotRecognized(p) => write!(f, "unknown permission: {p}"),
        }
    }
}

impl std::error::Error for PackageError {}

/// Validate a parsed manifest for consistency.
pub fn validate_manifest(manifest: &MiniAppManifest) -> Result<(), PackageError> {
    if manifest.app_id.is_empty() {
        return Err(PackageError::InvalidManifest("app_id is required".into()));
    }
    if manifest.name.is_empty() {
        return Err(PackageError::InvalidManifest("name is required".into()));
    }
    if manifest.version.is_empty() {
        return Err(PackageError::InvalidManifest("version is required".into()));
    }
    if manifest.icon.is_empty() {
        return Err(PackageError::InvalidManifest("icon is required".into()));
    }
    if manifest.entry.is_empty() {
        return Err(PackageError::InvalidManifest("entry is required".into()));
    }
    if manifest.size_bytes > 5 * 1024 * 1024 {
        return Err(PackageError::PackageTooLarge);
    }
    // Validate known permissions
    let known: &[&str] = &[
        permissions::PROFILE_READ,
        permissions::LOCATION,
        permissions::SEND_MESSAGE,
        permissions::CAMERA,
        permissions::GALLERY,
        permissions::NETWORK,
    ];
    for p in &manifest.permissions {
        if !known.contains(&p.as_str()) {
            return Err(PackageError::PermissionNotRecognized(p.clone()));
        }
    }
    Ok(())
}

// ═══════════════════════════════════════════════════════════════════
// Tests
// ═══════════════════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_manifest_roundtrip() {
        let json = r#"{
            "app_id": "com.example.test",
            "name": "Test App",
            "version": "1.0.0",
            "description": "A test",
            "icon": "icon.png",
            "entry": "index.html",
            "permissions": ["user.profile.read"],
            "size_bytes": 1024,
            "developer": { "name": "Dev", "website": "https://example.com" }
        }"#;
        let manifest: MiniAppManifest = serde_json::from_str(json).unwrap();
        assert_eq!(manifest.app_id, "com.example.test");
        assert_eq!(manifest.permissions.len(), 1);
        assert!(manifest.developer.is_some());
    }

    #[test]
    fn test_validate_good_manifest() {
        let m = MiniAppManifest {
            app_id: "com.example.good".into(),
            name: "Good".into(),
            version: "0.1.0".into(),
            description: String::new(),
            icon: "icon.png".into(),
            entry: "index.html".into(),
            permissions: vec!["user.profile.read".into()],
            size_bytes: 100_000,
            developer: None,
        };
        assert!(validate_manifest(&m).is_ok());
    }

    #[test]
    fn test_validate_bad_permission() {
        let m = MiniAppManifest {
            app_id: "com.example.bad".into(),
            name: "Bad".into(),
            version: "0.1.0".into(),
            description: String::new(),
            icon: "icon.png".into(),
            entry: "index.html".into(),
            permissions: vec!["user.secret".into()],
            size_bytes: 100_000,
            developer: None,
        };
        assert!(validate_manifest(&m).is_err());
    }

    #[test]
    fn test_validate_too_large() {
        let m = MiniAppManifest {
            app_id: "com.example.large".into(),
            name: "Large".into(),
            version: "0.1.0".into(),
            description: String::new(),
            icon: "icon.png".into(),
            entry: "index.html".into(),
            permissions: vec![],
            size_bytes: 10_000_000, // 10 MB > 5 MB limit
            developer: None,
        };
        assert!(validate_manifest(&m).is_err());
    }

    #[test]
    fn test_permission_set() {
        let mut ps = PermissionSet::new();
        assert!(!ps.check("user.profile.read"));
        ps.grant("user.profile.read");
        assert!(ps.check("user.profile.read"));
        assert_eq!(ps.list(), vec!["user.profile.read"]);
    }

    #[test]
    fn test_bridge_request_serialize() {
        let req = JsBridgeRequest {
            id: "req_1".into(),
            method: "user.getProfile".into(),
            params: serde_json::json!({}),
        };
        let json = serde_json::to_string(&req).unwrap();
        assert!(json.contains("req_1"));
        assert!(json.contains("user.getProfile"));
    }

    #[test]
    fn test_bridge_outcome_deserialize_success() {
        let json = r#"{"id":"req_1","result":{"id":"alice"}}"#;
        let outcome: JsBridgeOutcome = serde_json::from_str(json).unwrap();
        match outcome {
            JsBridgeOutcome::Success(r) => assert_eq!(r.id, "req_1"),
            _ => panic!("expected Success"),
        }
    }

    #[test]
    fn test_bridge_outcome_deserialize_error() {
        let json = r#"{"id":"req_1","error":{"code":-1,"message":"denied"}}"#;
        let outcome: JsBridgeOutcome = serde_json::from_str(json).unwrap();
        match outcome {
            JsBridgeOutcome::Error(e) => assert_eq!(e.error.code, -1),
            _ => panic!("expected Error"),
        }
    }

    #[test]
    fn test_sandbox_config_from_manifest() {
        let m = MiniAppManifest {
            app_id: "com.example.sbox".into(),
            name: "Sandbox".into(),
            version: "0.1.0".into(),
            description: String::new(),
            icon: "icon.png".into(),
            entry: "index.html".into(),
            permissions: vec!["user.profile.read".into(), "media.camera".into()],
            size_bytes: 50_000,
            developer: None,
        };
        let config = SandboxConfig::from_manifest(&m, "/apps/sbox");
        assert_eq!(config.app_dir, "/apps/sbox");
        assert!(config.permissions.check("user.profile.read"));
        assert!(config.permissions.check("media.camera"));
        assert!(!config.permissions.check("message.send"));
    }
}
